id = input("ป้อน student ID: ")
name = input("ป้อน student Name: ")
birthday = int(input("ป้อน student Birthyear: "))
print("```````````````````")
print(f"ยินดีต้อนรับ {id} {name} ที่ sau")
print(f"คุณเกิดปี {birthday} แปลว่าคุณอายุ {(2023 - birthday)}")
print("```````````````````")
print("ยินดีต้อนรับ ", id, name, "ที่ sau")
print("คุณเกิดปี ", birthday, " แปลว่าคุณอายุ ", (2023 - birthday))
print("```````````````````")
print("ยินดีต้อนรับ " +' ' + id + name +' ' + "ที่ sau")
print("คุณเกิดปี " + ' ' +str(birthday) + ' '+ "แปลว่าคุณอายุ " +' '+ str(2023 - birthday))
print("```````````````````")
print("ยินดีต้อนรับ {} {} ที่ sau".format(id,name))
print("คุณเกิดปี {} แปลว่าคุณอายุ {}".format(birthday,(2023 - birthday)))
print("```````````````````")

