print("welcome to 'SAU'" ,end='')
print('welcome to "DTI"', end='')
print("`````````````````")
print('welcome to "SAU"')
print("welcome to 'DTI'")
print("`````````````````")
print(456)
print(456.2324)
print(True)
print(False)
print(15 * 10 * 2)
print(True or False and False)
